name: .NET Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.101'

    - name: Restore dependencies
      run: dotnet restore ClassLibraryProjects

    - name: Build
      run: dotnet build ClassLibraryProjects --no-restore

    - name: Run Tests
      run: dotnet test ClassLibraryProjects/ClassLibraryProjects.sln --no-build

    - name: Run Tests
      run: dotnet test ClassLibraryProjects/ClassLibraryProjects.sln --no-build
